package com.csse3200.game.areas;

import com.badlogic.gdx.math.GridPoint2;
import com.csse3200.game.entities.Entity;
import java.util.List;
import java.util.Map;

/**
 * Interface for map editors to provide invalid and water tiles for tower placement.
 */
public interface IMapEditor {
    /**
     * Returns a map of invalid tiles (e.g. path, barriers, snow, etc).
     */
    Map<String, GridPoint2> getInvalidTiles();

    /**
     * Returns a list of water tiles for raft tower placement.
     */
    List<GridPoint2> getWaterTiles();

    /**
     * Register the coordinates of the obstacles for getInvalidTiles() to return uniformly.
     */
    void registerBarrierCoords(int[][] coords);

    /**
     * Register the snow tree coordinates for getInvalidTiles() to return uniformly.
     */
    void registerSnowTreeCoords(int[][] coords);

    /**
     * Generate enemy path for the map.
     */
    void generateEnemyPath();

    /**
     * Expose current waypoint list generated by the map editor, for save/load rebinding.
     */
    List<Entity> getWaypointList();

    /**
     * Returns the list of tiles that apply a speed modifier (slow zones).
     */
    List<GridPoint2> getSlowZoneTiles();

    /**
     * Set path layer opacity设置路径图层透明度
     * @param opacity 透明度值，范围0.0-1.0，0.0为完全透明，1.0为完全不透明
     */
    void setPathLayerOpacity(float opacity);

    /** ✅ 新增：判断某个格子是否为“普通路径格” */
    boolean isPath(int x, int y);

    /** ✅ 新增：只返回由 createPathTile(...) 写入的“普通路径格”坐标 */
    List<GridPoint2> getPathTiles();

}
